// Mocks generated by Mockito 5.0.16 from annotations
// in cleannewsapp/test/data/datasources/remote_news_datasource_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:cleannewsapp/external/infra/http_adapter.dart' as _i3;
import 'package:cleannewsapp/external/infra/http_client.dart' as _i5;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeDio_0 extends _i1.Fake implements _i2.Dio {}

/// A class which mocks [HttpAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpAdapter extends _i1.Mock implements _i3.HttpAdapter {
  MockHttpAdapter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(Invocation.getter(#dio), returnValue: _FakeDio_0())
          as _i2.Dio);
  @override
  _i4.Future<Map<String, dynamic>> request(
          {String? url, _i5.HttpMethod? method}) =>
      (super.noSuchMethod(
              Invocation.method(#request, [], {#url: url, #method: method}),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i4.Future<Map<String, dynamic>>);
  @override
  String toString() => super.toString();
}
