// Mocks generated by Mockito 5.0.16 from annotations
// in cleannewsapp/test/presentation/pages/home/home_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:cleannewsapp/domain/entities/news_entity.dart' as _i4;
import 'package:cleannewsapp/domain/repositories/news_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [NewsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsRepository extends _i1.Mock implements _i2.NewsRepository {
  MockNewsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.NewsEntity>> getNewsByCountry(String? country) =>
      (super.noSuchMethod(Invocation.method(#getNewsByCountry, [country]),
              returnValue:
                  Future<List<_i4.NewsEntity>>.value(<_i4.NewsEntity>[]))
          as _i3.Future<List<_i4.NewsEntity>>);
  @override
  String toString() => super.toString();
}
